code: python-for-beginners
title: Python for Beginners
toc:
  - code: anatomy-of-python-program
    title: Anatomy of Python Program
    id: 749811d4-356e-4593-97e7-669feb908d34
    topics:
      - code: introduction
        title: Introduction
        id: 91daf5f9-aee9-4225-ae78-8f61bc850036
      - code: values-and-operators
        title: Values and Operators
        id: cb5d3a1f-899d-49af-9ba2-fe8214491b8b
      - code: value-types-data-types
        title: Value Types / Data Types
        id: 273fc3c6-b82b-4026-8871-0dd669a6c573
      - code: expressions-and-statements
        title: Expressions and Statements
        id: 38010dfa-0e1c-4b06-a256-864103f4082c
      - code: conditional-operators
        title: Conditional Operators
        id: 2373d7d9-50f7-4f04-aec7-c0a814a58cce
      - code: functions
        title: Functions
        id: 31bdf3ee-498a-437b-8d98-0b28706fcbc6
      - code: variables
        title: Variables
        id: d4d97fe9-4151-40af-b71e-e4b8778cf86a
      - code: symbol-table
        title: Symbol Table
        id: 34f72f1b-b65a-4e0f-8a79-10ff9cc26396
      - code: taking-input
        title: Taking Input
        id: 5a9e3abc-f2fb-4030-8142-a01d1b86c0aa
      - code: data-type-conversion
        title: Data Type Conversion
        id: 5658979b-6898-4b36-8898-95147d4e36f2
  - code: python-control-statements
    title: Python Control Statements
    id: 4ed9366d-3c65-44cc-b1fb-2d9e2b6e5e7a
    topics:
      - code: introduction-1
        title: Introduction
        id: 3ba328ce-bdfc-46f3-8fbd-3cec1cbad236
      - code: if-elif-else
        title: 'if, elif, else'
        id: a410274d-512e-4313-825f-cab8928becf4
      - code: while-loop
        title: While Loop
        id: bcc1a5ea-022b-4b96-9d77-bc2a0c0249c9
      - code: while-with-branching
        title: While With Branching
        id: 98252a94-2ac0-4a62-b963-8b041827ed5f
      - code: infinite-while-loop-with-break
        title: Infinite While Loop With Break
        id: 0075b283-7332-4812-b836-90840594efb7
      - code: while-loop-with-flag
        title: While Loop With Flag
        id: f27d77da-8280-451b-a6fb-6326eff704be
      - code: star-patterns
        title: Star Patterns
        id: eafc527c-2d83-44fc-b3b6-54a760c9626c
  - code: list-of-values
    title: List of Values
    id: c2afb952-06e4-4060-9c5d-a764c6267c2b
    topics:
      - code: introduction-2
        title: Introduction
        id: 1e333ebe-8583-462b-95e6-d68d20717ef5
      - code: organizing-values-as-list
        title: Organizing Values as List
        id: 027c3927-b1df-4bdb-8f11-d5bf0e1de8ea
      - code: what-you-can-do-with-lists
        title: What You Can Do With Lists
        id: d35b693a-b2ae-42ab-9d95-e3c24bfd6662
      - code: list-indexing
        title: List Indexing
        id: 1360a4bd-1807-4d4c-b678-3e105603ec36
      - code: mental-model-for-lists
        title: Mental Model for Lists
        id: 3a565bc1-003b-4c4f-a047-cbd7f029f08a
      - code: list-slicing
        title: List Slicing
        id: 11501ae9-88eb-41d5-9b1c-e4a362854792
      - code: list-operations
        title: List Operations
        id: 4d394191-d7b7-41cd-bf09-b2d6234df8af
      - code: list-membership
        title: List Membership
        id: 1d7aec62-440a-4faf-83cf-a2dcdfa58edb
      - code: list-iteration
        title: List Iteration
        id: 9e2b93cb-dea0-4946-8f0d-ae70e8a0904f
      - code: list-iteration-with-index
        title: List Iteration With Index
        id: 62edf720-a4fe-4050-a366-8725bb29a09e
      - code: sequence-of-numbers
        title: Sequence of Numbers
        id: 872a0fa5-b466-463c-8ead-0c645ebfda80
      - code: list-traversal-with-range
        title: List Traversal With Range
        id: 5148aa6f-4977-4ed3-a832-8a673dc9f378
  - code: about
    title: About
    id: ef9eb7ec-91fb-423a-bb6c-9f551e312128
    topics:
      - code: author
        title: Author
        id: 8c509f75-be33-4179-944a-9d6e99d9251e
