code: python-for-beginners
title: Python for Beginners
toc:
  - code: anatomy-of-python-program
    title: Anatomy of Python Program
    id: 749811d4-356e-4593-97e7-669feb908d34
    topics:
      - code: introduction
        title: Introduction
        id: 91daf5f9-aee9-4225-ae78-8f61bc850036
      - code: values-and-operators
        title: Values and Operators
        id: cb5d3a1f-899d-49af-9ba2-fe8214491b8b
      - code: value-types-data-types
        title: Value Types / Data Types
        id: 273fc3c6-b82b-4026-8871-0dd669a6c573
      - code: expressions-and-statements
        title: Expressions and Statements
        id: 38010dfa-0e1c-4b06-a256-864103f4082c
      - code: conditional-operators
        title: Conditional Operators
        id: 2373d7d9-50f7-4f04-aec7-c0a814a58cce
      - code: functions
        title: Functions
        id: 31bdf3ee-498a-437b-8d98-0b28706fcbc6
      - code: variables
        title: Variables
        id: d4d97fe9-4151-40af-b71e-e4b8778cf86a
      - code: symbol-table
        title: Symbol Table
        id: 34f72f1b-b65a-4e0f-8a79-10ff9cc26396
      - code: taking-input
        title: Taking Input
        id: 5a9e3abc-f2fb-4030-8142-a01d1b86c0aa
      - code: data-type-conversion
        title: Data Type Conversion
        id: 5658979b-6898-4b36-8898-95147d4e36f2
  - code: python-control-statements
    title: Python Control Statements
    id: 4ed9366d-3c65-44cc-b1fb-2d9e2b6e5e7a
    topics:
      - code: introduction-1
        title: Introduction
        id: 3ba328ce-bdfc-46f3-8fbd-3cec1cbad236
  - code: about
    title: About
    id: ef9eb7ec-91fb-423a-bb6c-9f551e312128
    topics:
      - code: author
        title: Author
        id: 8c509f75-be33-4179-944a-9d6e99d9251e
