code: python-for-beginners
title: Python for Beginners
toc:
  - code: anatomy-of-python-program
    title: Anatomy of Python Program
    id: 749811d4-356e-4593-97e7-669feb908d34
    topics:
      - code: introduction
        title: Introduction
        id: 91daf5f9-aee9-4225-ae78-8f61bc850036
      - code: values-and-operators
        title: Values and Operators
        id: cb5d3a1f-899d-49af-9ba2-fe8214491b8b
      - code: value-types-data-types
        title: Value Types / Data Types
        id: 273fc3c6-b82b-4026-8871-0dd669a6c573
      - code: expressions-and-statements
        title: Expressions and Statements
        id: 38010dfa-0e1c-4b06-a256-864103f4082c
      - code: conditional-operators
        title: Conditional Operators
        id: 2373d7d9-50f7-4f04-aec7-c0a814a58cce
      - code: functions
        title: Functions
        id: 31bdf3ee-498a-437b-8d98-0b28706fcbc6
      - code: variables
        title: Variables
        id: d4d97fe9-4151-40af-b71e-e4b8778cf86a
      - code: symbol-table
        title: Symbol Table
        id: 34f72f1b-b65a-4e0f-8a79-10ff9cc26396
      - code: taking-input
        title: Taking Input
        id: 5a9e3abc-f2fb-4030-8142-a01d1b86c0aa
      - code: data-type-conversion
        title: Data Type Conversion
        id: 5658979b-6898-4b36-8898-95147d4e36f2
  - code: python-control-statements
    title: Python Control Statements
    id: 4ed9366d-3c65-44cc-b1fb-2d9e2b6e5e7a
    topics:
      - code: introduction-1
        title: Introduction
        id: 3ba328ce-bdfc-46f3-8fbd-3cec1cbad236
      - code: if-elif-else
        title: 'if, elif, else'
        id: a410274d-512e-4313-825f-cab8928becf4
      - code: while-loop
        title: While Loop
        id: bcc1a5ea-022b-4b96-9d77-bc2a0c0249c9
      - code: while-with-branching
        title: While With Branching
        id: 98252a94-2ac0-4a62-b963-8b041827ed5f
      - code: infinite-while-loop-with-break
        title: Infinite While Loop With Break
        id: 0075b283-7332-4812-b836-90840594efb7
      - code: while-loop-with-flag
        title: While Loop With Flag
        id: f27d77da-8280-451b-a6fb-6326eff704be
      - code: star-patterns
        title: Star Patterns
        id: eafc527c-2d83-44fc-b3b6-54a760c9626c
  - code: list-of-values
    title: List of Values
    id: c2afb952-06e4-4060-9c5d-a764c6267c2b
    topics:
      - code: introduction-2
        title: Introduction
        id: 1e333ebe-8583-462b-95e6-d68d20717ef5
      - code: organizing-values-as-list
        title: Organizing Values as List
        id: 027c3927-b1df-4bdb-8f11-d5bf0e1de8ea
      - code: what-you-can-do-with-lists
        title: What You Can Do With Lists
        id: d35b693a-b2ae-42ab-9d95-e3c24bfd6662
      - code: list-indexing
        title: List Indexing
        id: 1360a4bd-1807-4d4c-b678-3e105603ec36
      - code: mental-model-for-lists
        title: Mental Model for Lists
        id: 3a565bc1-003b-4c4f-a047-cbd7f029f08a
      - code: list-slicing
        title: List Slicing
        id: 11501ae9-88eb-41d5-9b1c-e4a362854792
      - code: list-operations
        title: List Operations
        id: 4d394191-d7b7-41cd-bf09-b2d6234df8af
      - code: list-membership
        title: List Membership
        id: 1d7aec62-440a-4faf-83cf-a2dcdfa58edb
      - code: list-iteration
        title: List Iteration
        id: 9e2b93cb-dea0-4946-8f0d-ae70e8a0904f
      - code: list-iteration-with-index
        title: List Iteration With Index
        id: 62edf720-a4fe-4050-a366-8725bb29a09e
      - code: sequence-of-numbers
        title: Sequence of Numbers
        id: 872a0fa5-b466-463c-8ead-0c645ebfda80
      - code: list-traversal-with-range
        title: List Traversal With Range
        id: 5148aa6f-4977-4ed3-a832-8a673dc9f378
      - code: tuple
        title: Tuple
        id: 15ac6fc4-b00f-448e-ac31-dbe106a0a161
      - code: set
        title: Set
        id: 7a941267-7ede-4109-8e02-b8f57b4baa73
      - code: comprehension
        title: Comprehension
        id: 7c054cca-c7fe-4e85-a3d0-0551ad7e1529
  - code: dictionary
    title: Dictionary
    id: 7712447d-3f3f-4c24-814d-f6211e704363
    topics:
      - code: mental-model-for-map
        title: Mental Model for Map
        id: 26d1baec-d686-4dc5-895b-5693114cff45
      - code: organize-map-as-list
        title: Organize Map As List
        id: 3634389e-ee64-4947-b690-113f3031a8aa
      - code: dict-as-map
        title: Dict As Map
        id: 4cc2fd0b-3e92-4c97-9cad-7a746ce1f2b1
      - code: dict-iteration
        title: Dict Iteration
        id: 3dad51b4-30cd-4a5b-b34f-8d9c86b506e4
      - code: dict-problems
        title: Dict Problems
        id: 5663e2b6-9574-4f04-8b70-6b0182becf79
  - code: python-strings
    title: Python Strings
    id: 785d9d1d-12fd-4bb9-9f27-14b66df9358f
    topics:
      - code: introduction-3
        title: Introduction
        id: f1234337-83bf-4d54-a51d-cf241ae1125d
      - code: creating-strings
        title: Creating Strings
        id: 0b2f5bc1-8e34-4c94-87f4-3baf7cd965b8
      - code: string-as-sequence
        title: String As Sequence
        id: bfcbdf49-c4de-4f64-80df-000d444a9078
      - code: matching-searching
        title: Matching / Searching
        id: 15ff58e7-347e-4df4-9b3e-a3a66e88c6ca
      - code: splitting
        title: Splitting
        id: ef32dac1-6f10-4b18-ac42-ee92caecc91d
      - code: joining
        title: Joining
        id: 459d6eca-32d2-40db-beef-57797000966a
      - code: stripping
        title: Stripping
        id: cad54446-1c16-4dde-9765-b1e71a84efff
      - code: formatting
        title: Formatting
        id: b3010050-38b5-4298-a85c-8eebf89032a9
  - code: python-functions
    title: Python Functions
    id: 0c99cbec-bbc5-44df-b397-e27411d0e431
    topics:
      - code: introduction-4
        title: Introduction
        id: df9d53c6-88b7-4f03-81fc-f067224a70e4
      - code: simple-functions
        title: Simple Functions
        id: 697425ff-e3e3-4b29-8bf6-d985a1815529
      - code: multiple-return-values
        title: Multiple Return Values
        id: 0330fa96-67fe-4b66-90f3-b00bfa676d77
      - code: variable-positional-arguments
        title: Variable Positional Arguments
        id: 224a10d5-d9a9-48bb-ac95-4ede50e2e498
      - code: variable-named-arguments
        title: Variable Named Arguments
        id: 5e71f0d8-a8d2-4d9f-a8c9-5773aadc4d74
      - code: default-value
        title: Default Value
        id: f6e169fd-f828-4e8f-9833-4e871efbcf73
      - code: recursion
        title: Recursion
        id: cf77eddc-3f38-4bf6-a2df-6b13cae9f893
  - code: sorting-in-python
    title: Sorting in Python
    id: 2a06a660-0166-44af-978a-33295587a294
    topics:
      - code: introduction-5
        title: Introduction
        id: 3fc91c73-cb53-4557-94b5-ef6e21216ab9
      - code: sorted()
        title: sorted()
        id: 0a502cac-2088-420e-a9fe-1e342f85b337
      - code: reversed-order
        title: Reversed Order
        id: 2f255c4a-24df-4d37-8ef2-5c00ab2607ac
      - code: custom-comparison
        title: Custom Comparison
        id: 896eb906-d6a1-409c-9fce-122c5a2419e9
      - code: list-of-dictionaries
        title: List of Dictionaries
        id: f3d2195e-3819-42cb-9939-63dbf8c79706
      - code: dict-by-values
        title: Dict by Values
        id: 051e7b4f-ce3b-450e-9f04-024de7217a1a
  - code: python-list-problems
    title: Python List Problems
    id: 1eea9f4c-87c8-491c-875b-9553ec1dc819
    topics:
      - code: introduction-6
        title: Introduction
        id: eda6264a-dc7e-4e5b-a4e9-f3c0afb96abe
      - code: about-list
        title: About List
        id: 2b58c78d-d9c0-4451-8485-886552dac9fd
      - code: list-and-dict-transformation
        title: List & Dict Transformation
        id: 29f3dcf9-9a7c-408b-9701-8baddd6bfdc7
      - code: pattern-in-list
        title: Pattern in List
        id: ff3b0f94-9dd8-4689-987c-f5b409dc0a61
      - code: nested-traversal
        title: Nested Traversal
        id: b4ced0c6-6484-44eb-9580-b6d1b38df198
      - code: list-manipulation
        title: List Manipulation
        id: fe42ad93-fe6a-43b4-915a-2c52e7d28f64
  - code: python-class
    title: Python Class
    id: c6e75523-a9f4-404b-82a9-5136b483473a
    topics:
      - code: value-types
        title: Value Types
        id: e9973d59-47c7-4e7f-bf74-34f742bd90f4
      - code: initializing-an-object
        title: Initializing an Object
        id: 102938c6-a419-4f33-a9a8-d799aaf3bf38
      - code: methods
        title: Methods
        id: a3fe5ecf-b6ea-428f-989d-85c63c7947f6
      - code: methods-with-arguments
        title: Methods With Arguments
        id: ed8cae92-4d03-4990-af2b-894012342d30
  - code: about
    title: About
    id: ef9eb7ec-91fb-423a-bb6c-9f551e312128
    topics:
      - code: author
        title: Author
        id: 8c509f75-be33-4179-944a-9d6e99d9251e
