code: python-for-beginners
title: Python for Beginners
toc:
  - code: anatomy-of-python-program
    title: Anatomy of Python Program
    id: 749811d4-356e-4593-97e7-669feb908d34
    topics:
      - code: introduction
        title: Introduction
        id: 91daf5f9-aee9-4225-ae78-8f61bc850036
      - code: values-and-operators
        title: Values and Operators
        id: cb5d3a1f-899d-49af-9ba2-fe8214491b8b
      - code: value-types-data-types
        title: Value Types / Data Types
        id: 273fc3c6-b82b-4026-8871-0dd669a6c573
      - code: expressions-and-statements
        title: Expressions and Statements
        id: 38010dfa-0e1c-4b06-a256-864103f4082c
      - code: conditional-operators
        title: Conditional Operators
        id: 2373d7d9-50f7-4f04-aec7-c0a814a58cce
  - code: about
    title: About
    id: ef9eb7ec-91fb-423a-bb6c-9f551e312128
    topics:
      - code: author
        title: Author
        id: 8c509f75-be33-4179-944a-9d6e99d9251e
